"""Employee add ondelete delete contact

Revision ID: 0215b8a0e640
Revises: 7967cf71460f
Create Date: 2023-11-11 15:09:59.482680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0215b8a0e640'
down_revision: Union[str, None] = '7967cf71460f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
