"""connect with employee

Revision ID: 0596113a1848
Revises: 7960ff06b17f
Create Date: 2023-12-01 02:28:35.237370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0596113a1848'
down_revision: Union[str, None] = '7960ff06b17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Clients', 'Employees', ['commercial_employee_id'], ['employee_id'])
    op.add_column('Contracts', sa.Column('commercial_employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Contracts', 'Employees', ['commercial_employee_id'], ['employee_id'])
    op.create_foreign_key(None, 'Events', 'Employees', ['support_employee_id'], ['employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Events', type_='foreignkey')
    op.drop_constraint(None, 'Contracts', type_='foreignkey')
    op.drop_column('Contracts', 'commercial_employee_id')
    op.drop_constraint(None, 'Clients', type_='foreignkey')
    # ### end Alembic commands ###
