"""Employee add ondelete delete contact

Revision ID: 50fe64f068df
Revises: a5cdeaf1a96c
Create Date: 2023-11-11 14:25:01.700439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fe64f068df'
down_revision: Union[str, None] = 'a5cdeaf1a96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
