"""Add department relationship to Employee

Revision ID: 6babb6c37875
Revises: 04dc1aecc8a5
Create Date: 2023-11-12 13:25:15.243251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6babb6c37875'
down_revision: Union[str, None] = '04dc1aecc8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
