"""delete event client contact no need anymore

Revision ID: 7960ff06b17f
Revises: a090b0ba2edc
Create Date: 2023-11-30 19:15:01.429591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7960ff06b17f'
down_revision: Union[str, None] = 'a090b0ba2edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Events_client_id_fkey', 'Events', type_='foreignkey')
    op.drop_column('Events', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Events_client_id_fkey', 'Events', 'Clients', ['client_id'], ['client_id'])
    # ### end Alembic commands ###
