"""Employee add ondelete delete contact

Revision ID: 7967cf71460f
Revises: 50fe64f068df
Create Date: 2023-11-11 14:51:09.838163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7967cf71460f'
down_revision: Union[str, None] = '50fe64f068df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
