"""Employee add ondelete delete contact

Revision ID: 892670d6b826
Revises: 0215b8a0e640
Create Date: 2023-11-11 15:14:34.970610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892670d6b826'
down_revision: Union[str, None] = '0215b8a0e640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Employees_contact_id_fkey', 'Employees', type_='foreignkey')
    op.drop_column('Employees', 'contact_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employees', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Employees_contact_id_fkey', 'Employees', 'Contacts', ['contact_id'], ['contact_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
