"""deleted commercial employee in contract

Revision ID: 9b9283433ef6
Revises: 63932f4c0c43
Create Date: 2023-11-27 15:34:41.430762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9283433ef6'
down_revision: Union[str, None] = '63932f4c0c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Contracts', 'commercial_employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contracts', sa.Column('commercial_employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
