"""delete event contact_id no need anymore

Revision ID: a090b0ba2edc
Revises: a589ef42451c
Create Date: 2023-11-30 19:07:55.865006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a090b0ba2edc'
down_revision: Union[str, None] = 'a589ef42451c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Events_event_contact_id_fkey', 'Events', type_='foreignkey')
    op.drop_column('Events', 'event_contact_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('event_contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Events_event_contact_id_fkey', 'Events', 'Contacts', ['event_contact_id'], ['contact_id'])
    # ### end Alembic commands ###
