"""your_migration_name

Revision ID: a589ef42451c
Revises: 9b9283433ef6
Create Date: 2023-11-28 17:23:12.186904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a589ef42451c'
down_revision: Union[str, None] = '9b9283433ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Clients_client_contact_id_fkey', 'Clients', type_='foreignkey')
    op.create_foreign_key(None, 'Clients', 'Contacts', ['client_contact_id'], ['contact_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Clients', type_='foreignkey')
    op.create_foreign_key('Clients_client_contact_id_fkey', 'Clients', 'Contacts', ['client_contact_id'], ['contact_id'])
    # ### end Alembic commands ###
