"""Employee add ondelete delete contact

Revision ID: a5cdeaf1a96c
Revises: ef9d46b6dc69
Create Date: 2023-11-11 14:01:35.108979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cdeaf1a96c'
down_revision: Union[str, None] = 'ef9d46b6dc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
