"""Employee add ondelete delete contact

Revision ID: ef9d46b6dc69
Revises: afcf5669912d
Create Date: 2023-11-11 13:52:40.160632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9d46b6dc69'
down_revision: Union[str, None] = 'afcf5669912d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Employees_contact_id_fkey', 'Employees', type_='foreignkey')
    op.create_foreign_key(None, 'Employees', 'Contacts', ['contact_id'], ['contact_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Employees', type_='foreignkey')
    op.create_foreign_key('Employees_contact_id_fkey', 'Employees', 'Contacts', ['contact_id'], ['contact_id'])
    # ### end Alembic commands ###
